import Image from 'next/image';
import LinkButton from '../ui/button/LinkButton';
import RevealAnimation from '../animation/RevealAnimation';

const services = [
  { title: 'Traino auto', slug: 'traino-auto', text: 'Portiamo la vettura verso officina, carrozzeria, deposito o destinazione concordata, proteggendo il mezzo durante il carico e il trasporto.', image: '/images/services/traino-auto.webp', secondary: '/images/services/trasporto-veicoli.webp' },
  { title: 'Carroattrezzi moto', slug: 'carroattrezzi-moto', text: 'Moto e scooter richiedono fissaggi e attenzioni diverse: organizziamo il recupero anche quando il mezzo è caduto o non può ripartire.', image: '/images/services/carroattrezzi-moto.webp', secondary: '/images/services/assistenza-veicoli-bloccati.webp' },
  { title: 'Recupero auto in panne', slug: 'recupero-auto-in-panne', text: 'Dal guasto improvviso alla vettura bloccata in parcheggio, valutiamo accesso, peso e condizioni prima di inviare il mezzo corretto.', image: '/images/services/recupero-auto-in-panne.webp', secondary: '/images/services/assistenza-veicoli-bloccati.webp' },
];

export default function Services() { return <section id="servizi" className="bg-background-2 dark:bg-background-5 py-[60px] lg:py-[100px]"><div className="main-container"><div className="mb-10 space-y-5 text-center md:mb-[70px]"><RevealAnimation delay={0.1}><span className="badge badge-green">Servizi carroattrezzi</span></RevealAnimation><RevealAnimation delay={0.2}><h2>Una risposta ordinata per ogni tipo di fermo</h2></RevealAnimation></div><div className="space-y-[42px]">{services.map((service, index) => <RevealAnimation key={service.slug} delay={0.3 + index * 0.1}><article className="border-stroke-1 bg-background-1 dark:bg-background-6 dark:border-stroke-8 rounded-[20px] border p-5 md:p-8 lg:p-[42px]"><div className="grid grid-cols-12 items-center gap-y-8 md:gap-14 lg:gap-20"><div className="col-span-12 md:col-span-6"><div className="space-y-8"><div className="space-y-3"><h3 className="text-heading-3 font-normal">{service.title}</h3><p className="max-w-[450px]">{service.text}</p></div><LinkButton href={`/servizi/${service.slug}`} className="btn btn-primary hover:btn-secondary btn-md w-[90%] sm:w-auto">Scopri il servizio</LinkButton></div></div><div className="col-span-12 md:col-span-6"><div className="flex items-center justify-end gap-5 lg:gap-8"><Image src={service.image} alt={service.title} width={420} height={520} className="w-full max-w-[210px] rounded-2xl object-cover" /><Image src={service.secondary} alt={`${service.title} in azione`} width={520} height={420} className="hidden w-full max-w-[320px] rounded-2xl object-cover sm:block" /></div></div></div></article></RevealAnimation>)}</div></div></section>; }
